# Generated by Django 5.2 on 2025-05-04 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('ollama_model', 'Ollama Model'), ('python_code', 'Python Code')], max_length=50)),
                ('order', models.IntegerField()),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Flow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='Pending', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OllamaModelBlock',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('aiflow.block',),
        ),
        migrations.CreateModel(
            name='PythonCodeBlock',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('aiflow.block',),
        ),
        migrations.AddField(
            model_name='block',
            name='flow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='aiflow.flow'),
        ),
        migrations.CreateModel(
            name='OllamaModelConfig',
            fields=[
                ('block', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='ollamamodelconfig', serialize=False, to='aiflow.ollamamodelblock')),
                ('model_name', models.CharField(max_length=255)),
                ('prompt', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PythonCodeConfig',
            fields=[
                ('block', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='pythoncodeconfig', serialize=False, to='aiflow.pythoncodeblock')),
                ('code', models.TextField()),
            ],
        ),
    ]
